WITH RECURSIVE CTE (ID, GENE) AS (
    SELECT ED.ID AS ID, 1 AS GENE
    FROM ECOLI_DATA AS ED
    WHERE ED.PARENT_ID IS NULL
    UNION ALL
    SELECT ED2.ID AS ID, CTE.GENE + 1
    FROM CTE
    INNER JOIN ECOLI_DATA AS ED2
    ON CTE.ID = ED2.PARENT_ID
    WHERE CTE.GENE < 4
)

SELECT ID
FROM CTE
WHERE GENE = 3
ORDER BY ID;