SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, FLOOR(CRCC.DAILY_FEE*30*((100 - DISCOUNT_RATE)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE AND CRCDP.DURATION_TYPE = '30일 이상'
WHERE CRCC.CAR_TYPE IN ('세단', 'SUV') AND
(FLOOR(CRCC.DAILY_FEE*30*((100 - DISCOUNT_RATE)/100)) BETWEEN 500000 AND 1999999) AND
CRCC.CAR_ID NOT IN (
    SELECT CRCRH.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
    WHERE '2022-11' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m') AND DATE_FORMAT(END_DATE, '%Y-%m')
)
ORDER BY FEE DESC, CRCC.CAR_TYPE, CRCC.CAR_ID DESC;