SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, TRUNCATE(CRCC.DAILY_FEE*30*(100-CRCDP.DISCOUNT_RATE)*0.01, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE AND CRCDP.DURATION_TYPE = '30일 이상'
WHERE CRCC.CAR_TYPE IN ('세단', 'SUV') AND 
CRCC.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-11' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m') AND DATE_FORMAT(END_DATE, '%Y-%m')
) AND (TRUNCATE(CRCC.DAILY_FEE*30*(100-CRCDP.DISCOUNT_RATE)*0.01, 0) BETWEEN 500000 AND 1999999)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;