WITH RENTAL_202211 AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '202211' BETWEEN DATE_FORMAT(START_DATE, '%Y%m') AND DATE_FORMAT(END_DATE, '%Y%m')
)

SELECT DISTINCT CRCC.CAR_ID AS CAR_ID, CRCC.CAR_TYPE AS CAR_TYPE, TRUNCATE((CRCC.DAILY_FEE*30)*(100-DISCOUNT_RATE)*0.01, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE TRUNCATE((CRCC.DAILY_FEE*30)*(100-DISCOUNT_RATE)*0.01, 0) BETWEEN 500000 AND 1999999 AND CRCC.CAR_TYPE IN ('세단', 'SUV') AND CRCC.CAR_ID NOT IN (SELECT CAR_ID FROM RENTAL_202211)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC