SELECT AI.ANIMAL_ID AS ANIMAL_ID, AI.ANIMAL_TYPE AS ANIMAL_TYPE, AI.NAME AS NAME
FROM ANIMAL_INS AS AI
LEFT JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME IS NOT NULL AND AI.SEX_UPON_INTAKE LIKE 'Intact%' AND (AO.SEX_UPON_OUTCOME LIKE 'Spayed%' OR AO.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID;