WITH RENTAL AS (
    SELECT DISTINCT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '20221016' BETWEEN DATE_FORMAT(START_DATE, '%Y%m%d') AND DATE_FORMAT(END_DATE, '%Y%m%d')
)

SELECT DISTINCT CRCRH.CAR_ID AS CAR_ID, COALESCE(AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
LEFT JOIN RENTAL R ON CRCRH.CAR_ID = R.CAR_ID
ORDER BY CAR_ID DESC;