WITH RENTALED_CAR AS (
    SELECT DISTINCT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)

SELECT DISTINCT CRCRH.CAR_ID AS CAR_ID, IFNULL(AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
LEFT JOIN RENTALED_CAR AS RC ON CRCRH.CAR_ID = RC.CAR_ID
ORDER BY CAR_ID DESC;