SELECT CONCAT(TRUNCATE((MONTH(DIFFERENTIATION_DATE)+2)/3, 0), 'Q') AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY CONCAT(TRUNCATE((MONTH(DIFFERENTIATION_DATE)+2)/3, 0), 'Q')
ORDER BY QUARTER