SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE*SUM(FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
INNER JOIN FOOD_ORDER AS FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y%m') = '202205'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID