SELECT HISTORY_ID, FLOOR(DAILY_FEE * (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) * IFNULL(1 - (DISCOUNT_RATE/100), 1)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
JOIN CAR_RENTAL_COMPANY_CAR AS CRCC
ON CRCRH.CAR_ID = CRCC.CAR_ID AND CRCC.CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE AND
((DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) BETWEEN 7 AND 29 AND CRCDP.DURATION_TYPE = '7일 이상') OR
(DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) BETWEEN 30 AND 89 AND CRCDP.DURATION_TYPE = '30일 이상') OR
(DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) >= 90 AND CRCDP.DURATION_TYPE = '90일 이상'))
ORDER BY FEE DESC, HISTORY_ID DESC;