WITH HISTORY_RANGE AS (
    SELECT HISTORY_ID, CAR_TYPE, DATEDIFF(END_DATE, START_DATE) + 1 AS TOTAL_DATE, 
    (DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE AS TOTAL_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
    INNER JOIN CAR_RENTAL_COMPANY_CAR AS CRCC
    ON CRCRH.CAR_ID = CRCC.CAR_ID
    WHERE CAR_TYPE = '트럭'
), DISCOUNT_PLAN AS (
    SELECT CAR_TYPE,
    CASE 
        WHEN DURATION_TYPE = '90일 이상' THEN 90
        WHEN DURATION_TYPE = '30일 이상' THEN 30
        WHEN DURATION_TYPE = '7일 이상' THEN 7
    END AS DURATION,
    (100-DISCOUNT_RATE)*0.01 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
)

SELECT HR.HISTORY_ID, TRUNCATE(TOTAL_FEE*MIN(IFNULL(DISCOUNT_RATE, 1)), 0) AS FEE
FROM HISTORY_RANGE AS HR
LEFT JOIN DISCOUNT_PLAN AS DP
ON HR.CAR_TYPE = DP.CAR_TYPE AND HR.TOTAL_DATE >= DP.DURATION
GROUP BY HR.HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;