SELECT HISTORY_ID, TRUNCATE(DAILY_FEE*(TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1)*(100-IFNULL(DISCOUNT_RATE, 0))*0.01, 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS CRCC
ON CRCRH.CAR_ID = CRCC.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE AND ((TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 BETWEEN 7 AND 29 AND DURATION_TYPE = '7일 이상')
OR (TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 BETWEEN 30 AND 89 AND DURATION_TYPE = '30일 이상')
OR (TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 90 AND DURATION_TYPE = '90일 이상'))
WHERE CRCC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC