WITH JULY_SUM AS (
    SELECT DISTINCT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT FH.FLAVOR AS FLAVOR
FROM FIRST_HALF AS FH
LEFT JOIN JULY_SUM AS JS ON FH.FLAVOR = JS.FLAVOR
ORDER BY (FH.TOTAL_ORDER + JS.TOTAL_ORDER) DESC
LIMIT 3