SELECT APNT_NO, PT_NAME, A.PT_NO AS PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AS A
JOIN PATIENT AS P ON A.PT_NO = P.PT_NO
JOIN DOCTOR AS D ON A.MDDR_ID = D.DR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y%m%d') = '20220413' AND A.MCDP_CD = 'CS' AND (APNT_CNCL_YN IS NULL OR APNT_CNCL_YN = 'N')
ORDER BY APNT_YMD