SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
JOIN PATIENT AS P
ON A.PT_NO = P.PT_NO AND APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
JOIN DOCTOR AS D
ON A.MDDR_ID = D. DR_ID
ORDER BY A.APNT_YMD;