WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)
SELECT H.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM HOURS AS H
LEFT JOIN ANIMAL_OUTS AS AO
ON H.HOUR = HOUR(AO.DATETIME)
GROUP BY H.HOUR;