SELECT DISTINCT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID AND
MONTH(CRCRH.START_DATE) = 10
WHERE CRCC.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;