SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS FI
INNER JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FNI.FISH_NAME, FI.LENGTH) IN (
    SELECT FNI.FISH_NAME, MAX(FI.LENGTH)
    FROM FISH_INFO AS FI
    INNER JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
    GROUP BY FNI.FISH_NAME
)