SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS DATE_FORMAT
FROM BOOK
WHERE CATEGORY = '인문' AND (PUBLISHED_DATE BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD') AND TO_DATE('2021-12-31', 'YYYY-MM-DD'))
ORDER BY PUBLISHED_DATE