SELECT UGB.TITLE AS TITLE, UGB.BOARD_ID AS BOARD_ID, UGR.REPLY_ID AS REPLY_ID, UGR.WRITER_ID AS WRITER_ID, UGR.CONTENTS AS CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS UGB
JOIN USED_GOODS_REPLY AS UGR
ON UGB.BOARD_ID = UGR.BOARD_ID
AND DATE_FORMAT(UGB.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY CREATED_DATE, TITLE;