SELECT UGB.TITLE AS TITLE, UGB.BOARD_ID AS BOARD_ID, UGR.REPLY_ID AS REPLY_ID, UGR.WRITER_ID AS WRITER_ID, UGR.CONTENTS AS CONTENTS, TO_CHAR(UGR.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_REPLY UGR
ON UGB.BOARD_ID = UGR.BOARD_ID AND TO_CHAR(UGB.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY CREATED_DATE, TITLE