SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS UGF
WHERE UGF.BOARD_ID = (
SELECT BOARD_ID
FROM USED_GOODS_BOARD AS UGB
ORDER BY UGB.VIEWS DESC
LIMIT 1
)
ORDER BY UGF.FILE_ID DESC;